// Generated by CoffeeScript 1.3.1
(function() {
  var Singleton;

  Singleton = (function() {

    Singleton.name = 'Singleton';

    function Singleton() {}

    Singleton.get = function() {
      var _ref;
      return (_ref = this.instance) != null ? _ref : this.instance = new this;
    };

    return Singleton;

  })();

  module.exports = Singleton;

}).call(this);
